"""Build/push images with `crane` (no Docker daemon needed).

ocr   : mirror ocr.source_image into <prefix>-vllm:mirror, then add one layer with
        /opt/serve.sh (generated from ocr.serve_args) as entrypoint -> :sagemaker
bench : runner.base_image + one layer with ocrbench and its dependencies installed
        for linux/amd64 (built locally with uv), optional extra CA -> <prefix>-bench:latest
"""

from __future__ import annotations

import io
import shlex
import shutil
import subprocess
import tarfile
import tempfile
from pathlib import Path

import boto3

from .config import ROOT, Config


def _crane() -> str:
    for c in (ROOT / ".tools" / "crane", shutil.which("crane")):
        if c and Path(c).exists():
            return str(c)
    raise SystemExit("crane not found — run `just tools`")


def _sh(*args: str, stdin: str | None = None) -> str:
    r = subprocess.run(args, input=stdin, text=True, capture_output=True)
    if r.returncode:
        raise SystemExit(f"{' '.join(args[:3])}... failed:\n{r.stderr[-2000:]}")
    return r.stdout.strip()


def login(cfg: Config) -> None:
    tok = boto3.client("ecr", region_name=cfg.region).get_authorization_token()["authorizationData"][0]
    import base64

    pw = base64.b64decode(tok["authorizationToken"]).decode().split(":", 1)[1]
    _sh(_crane(), "auth", "login", cfg.registry, "-u", "AWS", "--password-stdin", stdin=pw)


def _layer(files: dict[str, tuple[bytes, int]]) -> Path:
    """files: archive path -> (content, mode). Returns a tar.gz path."""
    out = Path(tempfile.mkdtemp()) / "layer.tgz"
    with tarfile.open(out, "w:gz", format=tarfile.USTAR_FORMAT) as tar:
        for name, (data, mode) in files.items():
            ti = tarfile.TarInfo(name)
            ti.size, ti.mode, ti.uid, ti.gid = len(data), mode, 0, 0
            tar.addfile(ti, io.BytesIO(data))
    return out


def serve_script(cfg: Config) -> str:
    o = cfg["ocr"]
    args = " \\\n  ".join(shlex.quote(a) for a in o.get("serve_args") or [])
    return f"""#!/bin/bash
# Generated by ocrbench from ocr.serve_args. SageMaker runs `<entrypoint> serve`;
# vLLM provides /ping and /invocations on :8080. Weights are mounted at /opt/ml/model.
set -euo pipefail
export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 VLLM_NO_USAGE_STATS=1 DO_NOT_TRACK=1
nvidia-smi || true
exec vllm serve /opt/ml/model \\
  --served-model-name {shlex.quote(o["served_model_name"])} \\
  {args} \\
  --host 0.0.0.0 --port 8080
"""


def build_ocr(cfg: Config, skip_mirror: bool = False) -> None:
    c, o = _crane(), cfg["ocr"]
    repo = f"{cfg.registry}/{cfg.ocr_repo}"
    login(cfg)
    if not skip_mirror:
        print(f"mirroring {o['source_image']} -> {repo}:mirror (streams through this machine)")
        _sh(c, "copy", "--platform", o.get("image_platform", "linux/amd64"), o["source_image"], f"{repo}:mirror")
    print(f"source digest: {_sh(c, 'digest', '--platform', o.get('image_platform', 'linux/amd64'), o['source_image'])}")
    layer = _layer({"opt/serve.sh": (serve_script(cfg).encode(), 0o755)})
    _sh(c, "append", "-b", f"{repo}:mirror", "-f", str(layer), "-t", f"{repo}:sagemaker-base")
    _sh(c, "mutate", f"{repo}:sagemaker-base", "--entrypoint", "/opt/serve.sh", "--cmd", "", "-t", f"{repo}:sagemaker")
    print(f"pushed {repo}:sagemaker ({_sh(c, 'digest', f'{repo}:sagemaker')})")


def build_bench(cfg: Config) -> None:
    c, r = _crane(), cfg["runner"]
    repo = f"{cfg.registry}/{cfg.bench_repo}"
    login(cfg)
    work = Path(tempfile.mkdtemp())
    site = work / "site"
    print("installing ocrbench + deps for linux/amd64 (uv)")
    _sh(
        "uv",
        "pip",
        "install",
        "--quiet",
        "--target",
        str(site),
        "--python-version",
        "3.12",
        "--python-platform",
        "x86_64-manylinux_2_28",
        "--no-cache",
        str(ROOT),
    )
    files: dict[str, tuple[bytes, int]] = {}
    for f in site.rglob("*"):
        if f.is_file() and "__pycache__" not in f.parts:
            files[f"opt/ocrbench/{f.relative_to(site).as_posix()}"] = (f.read_bytes(), 0o644)
    env = ["PYTHONPATH=/opt/ocrbench"]
    if r.get("extra_ca_pem"):
        pem = Path(r["extra_ca_pem"]).expanduser().read_bytes()
        files["opt/ocrbench-ca/extra.pem"] = (pem, 0o644)
        env.append("OCRBENCH_EXTRA_CA=/opt/ocrbench-ca/extra.pem")
    layer = _layer(files)
    print(f"layer: {layer.stat().st_size / 1e6:.1f} MB, {len(files)} files")
    _sh(c, "append", "--platform", "linux/amd64", "-b", r["base_image"], "-f", str(layer), "-t", f"{repo}:base")
    mut = [c, "mutate", f"{repo}:base", "-t", f"{repo}:latest", "--entrypoint", "python,-m,ocrbench.cli"]
    for e in env:
        mut += ["--env", e]
    _sh(*mut)
    print(f"pushed {repo}:latest ({_sh(c, 'digest', f'{repo}:latest')})")
